### ISSUE TITLE
demo link is broken

### ISSUE THREAD

**Issue by damisparks** [atinux/my-pull-requests#1]
The demo link is broken. [https://prs.atinux.com](https://prs.atinux.com)
EDIT! @atinux Maybe the app has not been deployed yet? 
<img width="1095" alt="image" src="https://github.com/user-attachments/assets/217b1bb1-02bb-486b-b85a-19f9952df26c">

**Comment by atinux** [comment]
You are too fast, I am still working on it :D

**Comment by atinux** [comment]
It's now live @damisparks
