### ISSUE TITLE
[Enquiry] directory partition

### ISSUE THREAD

**Issue by WuChenDi** [atinux/my-pull-requests#4]
Hi man, how are you.

I would like to ask how to put all the front-end in the `app` directory, i.e. on the same level as the `server`.

Is it necessary to depend on this package, `@nuxthub/core`

![image](https://github.com/user-attachments/assets/9933eda1-1208-4ddc-b003-c639103cf326)

**Comment by atinux** [comment]
Hi,

it is because I set the compatibility version of this project to Nuxt 4 and it has a new directory structure.

https://nuxt.com/docs/getting-started/upgrade#testing-nuxt-4
